Fix XSX and update XDC source for DEFUSE
ukaea/fair-mast-ingestion pull request #2
Opened 2024-08-12 15:46 UTC by samueljackson92

This changes the soft x-ray source code to fix a bug with adding camera params. This also removes most of the XDC processing for now. We only capture IPref as this is required by DEFUSE.

2024-08-13 07:19 UTC, jameshod5 requested changes

2024-08-13 07:19 UTC, jameshod5 commented on src/transforms.py
`test_xsx_camera_params` fails, believe it is because of line 304 or 310 (need to look into the logs). Changing the name maybe

2024-08-13 07:19 UTC, jameshod5 commented on src/transforms.py
more for curiosity, will we be re-introducing the tensorising bits later on then?

2024-08-13 07:31 UTC, samueljackson92 commented on src/transforms.py
Yea. Will fix this.

2024-08-13 07:32 UTC, samueljackson92 commented on src/transforms.py
Yes. But we've currently done this quite crudely. Nathan and I have some notes from talking to charlie vincent about `xdc`. We can do this a bit better than the current implementation. But it should not be done here. Here I just want to get the one signal that is important for DEFUSE.

2024-08-15 12:15 UTC, samueljackson92 commented
@jameshod5 I think this is ready to be re-reviewed please!

2024-08-15 12:24 UTC, jameshod5 commented
Looks okay to me

2024-08-15 12:24 UTC, merged