Add support for CSD3
ukaea/fair-mast-ingestion pull request #3
Opened 2024-08-15 12:17 UTC by samueljackson92

This removes the segfault handling code and adds jobscripts for CSD3.

To review:
 - Follow the setup & running instructions in the README
 - Code review.

2024-08-15 13:34 UTC, jameshod5 requested changes
`python -m pip install --U pip` - This doesn't work for me, have to use --upgrade instead. (or change to -U instead)

other two comments are more suggestions, but the above needs to be fixed

2024-08-15 13:34 UTC, jameshod5 commented on README.md
> +```
if you want it more foolproof perhaps add something to `cd ..` out of the mastcodes folder, the above step puts the user in mastcodes and not in the directory this step requires

2024-08-15 13:34 UTC, jameshod5 commented on README.md
> +sbatch ./jobs/ingest.csd3.slurm.sh campaign_shots/tiny_campaign.csv s3://mast/test/shots/ amc
User will need the .s5cfg file, not sure if that should be specified in the readme?

2024-08-19 07:18 UTC, samueljackson92 commented
I had added your suggestions to the README.

2024-08-19 07:49 UTC, jameshod5 commented
> `python -m pip install --U pip` - This doesn't work for me, have to use --upgrade instead. (or change to -U instead)
> 
> other two comments are more suggestions, but the above needs to be fixed

This still needs to change to `python -m pip install --upgrade pip` or `python -m pip install -U pip`

2024-08-19 07:52 UTC, samueljackson92 commented
Sorry missed that one!

2024-08-19 07:54 UTC, merged

2024-08-19 07:55 UTC, jameshod5 commented
Looks good, merged

2024-08-19 08:00 UTC, samueljackson92 commented
[heart]         Jackson, Samuel (Computing) reacted to your message:
________________________________
From: jameshod5 ***@***.***>
Sent: Monday, August 19, 2024 7:55:21 AM
To: ukaea/fair-mast-ingestion ***@***.***>
Cc: Jackson, Samuel (Computing) ***@***.***>; Author ***@***.***>
Subject: Re: [ukaea/fair-mast-ingestion] Add support for CSD3 (PR #3)


Looks good, merged

—
Reply to this email directly, view it on GitHub<https://github.com/ukaea/fair-mast-ingestion/pull/3#issuecomment-2295902746>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AAS7LZJFZCGKYELEXYPOYQLZSGQGTAVCNFSM6AAAAABMSDDGAOVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDEOJVHEYDENZUGY>.
You are receiving this because you authored the thread.Message ID: ***@***.***>